# vim: sw=2 et sts=2


image: alpine:latest

stages:
  - pre
  - deploy
  - post

variables:
  GIT_SUBMODULE_STRATEGY: normal


include:
  - remote: https://file.9009.xyz/gitlab/ci/get-404-page.yml
  - remote: https://file.9009.xyz/gitlab/ci/pages.yml
  - remote: https://file.9009.xyz/gitlab/ci/purge-cloudflare-cache.yml
