# vim: sw=2 et sts=2


image: alpine:latest

stages:
  - pre
  - deploy
  - post

variables:
  GIT_SUBMODULE_STRATEGY: normal


include:
  #- remote: https://file.9009.xyz/gitlab/ci/get-404-page.yml
  - local: gitlab/ci/minify-pages.yml
  #- local: gitlab/ci/minify.yml
  #- local: gitlab/ci/pages.yml
  #- local: gitlab/ci/purge-cloudflare-cache.yml
