# vim: sw=2 et sts=2

image: alpine:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -rv * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

include:
  - remote: https://file.0770.xyz/gitlab/ci/pages.yml
  - remote: https://file.0770.xyz/gitlab/ci/purge-cloudflare-cache.yml
