#!/usr/bin/env bash
#
# copy public key to ~/.ssh/authorized_keys

set -e

home=$HOME

url=https://9009.xyz/key



mkdir -p $home/.ssh
chmod 700 $home/.ssh

auth_keys_file="$home/.ssh/authorized_keys"

if [[ ! -f $auth_keys_file ]]; then
	touch $auth_keys_file
fi
chmod 600 $home/.ssh/authorized_keys

tmpfile=$(mktemp); trap "rm -rf $tmpdir" EXIT;  

add_pub_key() {
	local f=$1
	
	echo "begin downlad pubkey: $f"
	curl -4s -o $tmpfile $url/$1 

	local cnt=$(cat $tmpfile  | grep -P '^ssh-[ a-zA-Z0-9+=/@.]+$' | wc -l)
	if (( $cnt != 1 )); then
		echo -e "illegal ssh pub key:\n$(cat $tmpfile)" 1>&2
		exit 1
	fi

	if grep -q -F "$(cat $tmpfile)" $auth_keys_file; then
		echo "public key already added: $1"
	else
		cat $tmpfile >>$auth_keys_file
		echo "public key add succ: $1"
	fi
}


#add_pub_key "not"
add_pub_key "rsa.pub"
add_pub_key "ed25519.pub"


