# vim: set sw=2 sts=2 et:     
# encoding: utf-8

name: purge-cache
on: [push]

jobs:
  build:
    name: purge
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: purge
      run: |
        pwd
        ls -l
        find .
        ./purge-cache.sh

