# vim: sw=2 et sts=2


name: purge-cache
on: [push]

jobs:
  build:
    name: purge cloudflare cache
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: purge
      run: |
        pwd
        ls -l
        ./purge-cache.sh

